include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # 🔥 DESACTIVAR ADVERTENCIAS MOLESTAS
    use_build_context_synchronously: ignore
    curly_braces_in_flow_control_structures: ignore
    unnecessary_import: ignore
    unused_import: ignore
    unused_local_variable: ignore
    dead_code: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_declarations: ignore
    avoid_print: ignore
    unnecessary_this: ignore
    unnecessary_brace_in_string_interps: ignore
    prefer_typing_uninitialized_variables: ignore
    unnecessary_null_checks: ignore
    unnecessary_getters_setters: ignore
    prefer_final_fields: ignore
    prefer_final_locals: ignore
    non_constant_identifier_names: ignore
    sort_constructors_first: ignore
    sort_child_properties_last: ignore
    avoid_unnecessary_containers: ignore
    body_might_complete_normally_nullable: ignore
    library_private_types_in_public_api: ignore
    constant_identifier_names: ignore
    avoid_classes_with_only_static_members: ignore
    avoid_function_literals_in_foreach_calls: ignore
    deprecated_member_use: ignore

  # Opcional: evitar analizar carpetas que no te interesan
  exclude:
    - build/**
    - .dart_tool/**
    - ios/**
    - android/**
    - web/**

linter:
  rules:
    # 🔕 DESACTIVO TODAS LAS REGLAS DE ESTILO DE FLUTTER LINTS
    avoid_print: false
    prefer_single_quotes: false
