// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3ja097qL2-NMQmU9YQyVm5tKHNcLAt4',
    appId: '1:292933443019:web:cae61c9210f6b56fc26a4e',
    messagingSenderId: '292933443019',
    projectId: 'clubdeportivohuandoy',
    authDomain: 'clubdeportivohuandoy.firebaseapp.com',
    storageBucket: 'clubdeportivohuandoy.firebasestorage.app',
    measurementId: 'G-MYJTYG48LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrXgt9vfMipu5fJ1VQT6BQ76Iagl_glc',
    appId: '1:292933443019:android:c2c36cd22eccda4ac26a4e',
    messagingSenderId: '292933443019',
    projectId: 'clubdeportivohuandoy',
    storageBucket: 'clubdeportivohuandoy.firebasestorage.app',
  );

}